version: "3.7"

services:
  clinica2:
    build:
      context: .
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
    driver: "bridge"